# Generated by Django 3.1 on 2020-08-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_ammount',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='total_ammount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_ammount',
        ),
    ]
