# Generated by Django 3.1 on 2020-08-15 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(default='', max_length=50)),
                ('companylogo', models.ImageField(upload_to='CompanyProfile/%Y/%m/%d/')),
                ('address', models.TextField(default='')),
                ('country', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('currency', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager_name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='')),
                ('country', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('zipcode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='profile/%Y/%m/%d/')),
                ('address', models.TextField(default='')),
                ('country', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=15)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
