# Generated by Django 3.1 on 2020-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='shop_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
