# Generated by Django 3.1 on 2020-10-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_shopprofile_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='Manager_name',
        ),
    ]
