# Generated by Django 3.1 on 2020-08-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=255)),
                ('Slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=255)),
                ('Slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d/')),
                ('Slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qty', models.IntegerField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=4)),
                ('available', models.BooleanField()),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
