# Generated by Django 3.1 on 2020-08-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Category_Name',
            new_name='brand_Name',
        ),
    ]
